fragment AuthorInfo on AuthorType {
	name
	affiliation
}

query GetPapers {
	papers {
		id
		title
		authors {
			...AuthorInfo
		}
		abstract
		pubDate
		updatedDate
		categories
		links
		comment
		journalRef
		trendinessScore
	}
}
